set expandtab
set tabstop=4
set shiftwidth=4
set number

"execute pathogen#infect()
syntax on
filetype plugin indent on

let NERDTreeNodeDelimiter = "\t"
"map <C-p> :NERDTreeToggle<CR>
map <leader>tt :NERDTreeToggle<CR>
map <leader>aa :TagbarToggle<CR>
map <leader>xx :vert term<CR>


"set your tag file here
"set tags=/usr/src/linux-stable/tags

"colorscheme 256-jungle
packadd! dracula
syntax enable
colorscheme dracula
"colorscheme default

"Helptags

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

autocmd TerminalWinOpen *                                                                          
  \ if &buftype == 'terminal' |                                                                    
  \   resize 10 |                                                                                  
  \   setlocal termwinsize=0x140 |                                                                 
  \   setlocal nowrap |                                                                            
  \ endif                                                                                          
                                                                                                   
nnoremap <leader>t :belowright terminal<CR>
